---
title: "Shinylive"
format: live-html
filters:
  - shinylive
engine: knitr
---

# Shinylive...

## ... for Python

[Shinylive for Python (editor)](https://shinylive.io/py/examples/)

[Shinylive for Python (GitHub/documentation)](https://github.com/posit-dev/py-shinylive)

## ... for R

[Shinylive for R (editor)](https://shinylive.io/r/examples/)

[Shinylive for R (GitHub)](https://github.com/posit-dev/r-shinylive)

[Shinylive for R (documentation)](https://posit-dev.github.io/r-shinylive/)

# Quarto + Shinylive

Follow the instructions in the [Shinylive GitHub repository](https://github.com/quarto-ext/shinylive) to learn how to install the Shinylive package, install the Quarto extension, and learn how to embed a Shinylive app in a Quarto document. The [GitHub page for the repository](https://quarto-ext.github.io/shinylive/) has additional examples and documentation.

::: {.callout-note title="R example"}
The documentation above doesn't include the specific format for embedding a Shinylive R app in a Quarto document. The code snippet below is an example of how to do that. Note the use of the `shinylive-r` engine in the code chunk options.
:::

Additional link:

 - [coatless Quarto example](https://github.com/coatless-quarto/r-shinylive-demo)

```{shinylive-r}
#| standalone: true
#| viewerHeight: 600
library(shiny)
library(bslib)

# Define UI for app that draws a histogram ----
ui <- page_sidebar(
  sidebar = sidebar(open = "open",
    numericInput("n", "Sample count", 100),
    checkboxInput("pause", "Pause", FALSE),
  ),
  plotOutput("plot", width=1100)
)

server <- function(input, output, session) {
  data <- reactive({
    input$resample
    if (!isTRUE(input$pause)) {
      invalidateLater(1000)
    }
    rnorm(input$n)
  })
  
  output$plot <- renderPlot({
    hist(data(),
      breaks = 40,
      xlim = c(-2, 2),
      ylim = c(0, 1),
      lty = "blank",
      xlab = "value",
      freq = FALSE,
      main = ""
    )
    
    x <- seq(from = -2, to = 2, length.out = 500)
    y <- dnorm(x)
    lines(x, y, lwd=1.5)
    
    lwd <- 5
    abline(v=0, col="red", lwd=lwd, lty=2)
    abline(v=mean(data()), col="blue", lwd=lwd, lty=1)

    legend(legend = c("Normal", "Mean", "Sample mean"),
      col = c("black", "red", "blue"),
      lty = c(1, 2, 1),
      lwd = c(1, lwd, lwd),
      x = 1,
      y = 0.9
    )
  }, res=140)
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

<details>
<summary>Code</summary>
````
```{{shinylive-r}}
#| standalone: true
#| viewerHeight: 600
library(shiny)
library(bslib)

# Define UI for app that draws a histogram ----
ui <- page_sidebar(
  sidebar = sidebar(open = "open",
    numericInput("n", "Sample count", 100),
    checkboxInput("pause", "Pause", FALSE),
  ),
  plotOutput("plot", width=1100)
)

server <- function(input, output, session) {
  data <- reactive({
    input$resample
    if (!isTRUE(input$pause)) {
      invalidateLater(1000)
    }
    rnorm(input$n)
  })
  
  output$plot <- renderPlot({
    hist(data(),
      breaks = 40,
      xlim = c(-2, 2),
      ylim = c(0, 1),
      lty = "blank",
      xlab = "value",
      freq = FALSE,
      main = ""
    )
    
    x <- seq(from = -2, to = 2, length.out = 500)
    y <- dnorm(x)
    lines(x, y, lwd=1.5)
    
    lwd <- 5
    abline(v=0, col="red", lwd=lwd, lty=2)
    abline(v=mean(data()), col="blue", lwd=lwd, lty=1)

    legend(legend = c("Normal", "Mean", "Sample mean"),
      col = c("black", "red", "blue"),
      lty = c(1, 2, 1),
      lwd = c(1, lwd, lwd),
      x = 1,
      y = 0.9
    )
  }, res=140)
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```
````
</details>